export const tableOption = {
  reserveSelection: true,
  selectClearBtn: false,
  addBtn: false,
  header: false,
  editBtn: false,
  delBtn: false,
  align: 'center',
  menuWidth: 250,
  menuAlign: 'center',
  border: true,
  column: [{
    label: '用户ID',
    prop: 'createByNo',
    overHidden: true,
  }, {
    label: '账户名',
    prop: 'createByName',
    width: 150,
    overHidden: true,
  }, {
    label: '问题标题',
    prop: 'title',
    overHidden: true,
    width: 300,
    slot: true
  }, {
    label: '问题内容',
    prop: 'description',
    overHidden: true,
    width: 300,
  }, {
    label: '回复量(条)',
    prop: 'answerCount',
    overHidden: true,
  }, {
    label: '状态',
    overHidden: true,
    prop: 'deleted',
    slot: true
  }, {
    label: '提问时间',
    prop: 'createTime',
    type: 'datetime',
    overHidden: true,
    width: 120,
    format: 'yyyy-MM-dd HH:mm',
    valueFormat: 'yyyy-MM-dd HH:mm:ss'
  }, {
    label: '提问端口',
    prop: 'questionPort',
    overHidden: true,
  }, ]
}
