export const tableOption = {
  reserveSelection: true,
  selectClearBtn: false,
  refreshBtn: false,
  addBtn: false,
  header: false,
  editBtn: false,
  delBtn: false,
  header: false,
  align: 'center',
  menuAlign: 'center',
  menuWidth: 150,
  menu: false,
  border: true,
  // index: true,
  // indexLabel: '序号',
  column: [{
    label: '序号',
    prop: 'sort',
    overHidden: true,
    width: 50,
  }, {
    label: '链接名称',
    prop: 'linkName',
    slot: true,
    overHidden: true,
    width: 350,
  }, {
    label: '链接地址',
    prop: 'linkUrl',
    overHidden: true,
    slot: true,
  }, {
    prop: 'menu',
    overHidden: true,
    slot: true,
    headerSlot: 'menuHeader',
    width: 200,
  }, ]
}
