export default [
  {
    label: '阿里云图标',
    // list: [
    //   'el-icon-quanxianguanli',
    //   'icon-yonghuguanli',
    //   'icon-jiaoseguanli',
    //   'icon-web-icon-',
    //   'icon-xitongguanli',
    //   'icon-rizhiguanli',
    //   'icon-navicon-zdgl',
    //   'icon-weibiaoti46',
    //   'icon-miyue',
    //   'icon-shouji',
    //   'icon-miyue',
    //   'icon-denglvlingpai',
    //   'icon-luyou',
    //   'icon-msnui-supervise',
    //   'icon-server',
    //   'icon-wendang',
    //   'icon-gtsquanjushiwufuwuGTS',
    //   'icon-caidanguanli',
    //   'icon-guanwang',
    //   'icon-guanwangfangwen',
    //   'icon-guiji',
    //   'icon-fensiguanli',
    //   'icon-gongzhonghao',
    //   'icon-anniu_weixincaidanlianjie',
    //   'icon-weixincaidan',
    //   'icon-xiaoxiguanli',
    //   'icon-zhexiantu',
    //   'icon-canshu',
    //   'icon-erji-zuhushouye',
    //   'icon-pay6zhifu',
    //   'icon-zhifuqudaoguanli',
    //   'icon-dingdan',
    //   'icon-tuikuan',
    //   'icon-webicon14',
    //   'icon-shouyintai',
    //   'icon-wenjianguanli',
    //   'icon-mysql',
    //   'icon-shejiyukaifa-',
    //   'icon-record',
    //   'icon-biaodanbiaoqian',
    //   'icon-TagAdd',
    //   'icon-sucaisads',
    //   'icon-huifu'
    // ],
    list: [
      'el-icon-c-scale-to-original',
      'el-icon-date',
      'el-icon-folder',
      'el-icon-folder-opened',
      'el-icon-folder-add',
      'el-icon-folder-checked',
      'el-icon-tickets',
      'el-icon-document-remove',
      'el-icon-document-delete',
      'el-icon-document-copy',
      'el-icon-document-checked',
      'el-icon-document',
      'el-icon-printer',
      'el-icon-paperclip',
      'el-icon-takeaway-box',
      'el-icon-monitor',
      'el-icon-search',
      'el-icon-attract',
      'el-icon-mobile',
      'el-icon-scissors',
      'el-icon-umbrella',
      'el-icon-headset',
      'el-icon-brush',
      'el-icon-mouse',
      'el-icon-coordinate',
      'el-icon-magic-stick',
      'el-icon-reading',
      'el-icon-data-line',
      'el-icon-data-board',
      'el-icon-pie-chart',
      'el-icon-collection-tag',
      'el-icon-film',
      'el-icon-suitcase',
      'el-icon-receiving',
      'el-icon-collection',
      'el-icon-files',
      'el-icon-notebook-1',
      'el-icon-notebook-2',
      'el-icon-toilet-paper',
      'el-icon-office-building',
      'el-icon-school',
      'el-icon-table-lamp',
      'el-icon-house',
      'el-icon-shopping-cart-2',
      'el-icon-shopping-cart-1',
      'el-icon-shopping-bag-1',
      'el-icon-box',
      'el-icon-bank-card',
      'el-icon-coin',
      'el-icon-discount',
      'el-icon-price-tag',
      'el-icon-news',
      'el-icon-guide',
      'el-icon-male',
      'el-icon-female',
      'el-icon-cpu',
      'el-icon-link',
      'el-icon-connection',
      'el-icon-open',
      'el-icon-turn-off',
      'el-icon-set-up',
      'el-icon-chat-round',
      'el-icon-chat-line-round',
      'el-icon-chat-dot-round',
      'el-icon-chat-line-square',
      'el-icon-message',
      'el-icon-position',
      'el-icon-close-notification',
      'el-icon-time',
      'el-icon-odometer',
      'el-icon-copy-document',
      'el-icon-trophy',
      'el-icon-discover',
      'el-icon-place',
      'el-icon-alarm-clock',
      'el-icon-mobile-phone',
      'el-icon-unlock',
      'el-icon-lock',
      'el-icon-user-solid',
      'el-icon-user',
      'el-icon-s-order',
      'el-icon-s-platform',
      'el-icon-s-home',
      'el-icon-upload'
    ]
  }
]
