export const followOption = {
  reserveSelection: true,
  stripe: true,
  selectClearBtn: false,
  refreshBtn: false,
  addBtn: false,
  header: true,
  editBtn: false,
  delBtn: false,
  header: false,
  align: 'center',
  menuAlign: 'center',
  menuWidth: 150,
  border: true,
  column: [{
    label: '工号',
    prop: 'userNo',
    slot: true,
    sortable: true,
    overHidden: true,
  }, {
    label: '姓名',
    prop: 'userName',
    slot: true,
    overHidden: true,
  }, {
    label: '部门',
    prop: 'deptName',
    overHidden: true,
  }, {
    label: '客户跟进次数',
    prop: 'followCount',
    sortable: "custom",
    overHidden: true,
  }, {
    label: '关联回访次数',
    prop: 'visitCount',
    sortable: "custom",
    overHidden: true,
  }, {
    label: '服务满意度均分',
    prop: 'avgScore',
    sortable: "custom",
    overHidden: true,
  },]
}

export const perFollowOption = {
  reserveSelection: true,
  stripe: true,
  selectClearBtn: false,
  refreshBtn: false,
  addBtn: false,
  header: true,
  editBtn: false,
  delBtn: false,
  header: false,
  align: 'center',
  border: true,
  menuWidth: 120,
  column: [{
    label: '线索编号',
    prop: 'clueNo',
    width: 180,
    overHidden: true,
  }, {
    label: '客户名称',
    prop: 'authName',
    slot: true,
    overHidden: true,
    width: 180,
  }, {
    label: '线索类型',
    prop: 'clueType',
    slot: true,
    width: 100,
  }, {
    label: '联系人',
    prop: 'contactName',
    overHidden: true,
    width: 100,
  }, {
    label: '联系方式',
    prop: 'mobile',
    width: 100,
    overHidden: true,
  }, {
    label: '地区',
    prop: 'orgAddress',
    slot: true,
    width: 130,
    overHidden: true,
  }, {
    label: '线索归属',
    prop: 'clueAttributionEmpName',
    slot: true,
    width: 80,
  }, {
    label: '业务员',
    prop: 'clueSalesmanEmpName',
    slot: true,
    width: 80,
  }, {
    label: '跟进内容',
    prop: 'followContent',
    width: 160,
    overHidden: true,
  }, {
    label: '跟进方式',
    slot: true,
    prop: 'followTypeId',
  },
  {
    label: '跟进时间',
    prop: 'createTime',
    overHidden: true,
    sortable: "custom",
    slot: true,
    width: 140,
  },
  {
    label: '上次回访时间',
    prop: 'returnTime',
    overHidden: true,
    width: 140,
  }]
}
